name: Update README ⭐
on:
  schedule:
    - cron: "0 */2 * 12 *" 
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1.0.3
        with:
          userId: 1553676
          sessionCookie: ${{ secrets.AOC_SESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README stars
          file_pattern: README.md